package com.bigbasket.mobileapp.util;

public interface ApiErrorCodes {

    int POTENTIAL_ORDER_SLOT_EXPIRED = 100;
    int INTERNAL_SERVER_ERROR = 101;
    int INVALID_FIELD = 103;
    String INVALID_FIELD_STR = "103";
    int INVALID_USER = 104;
    int EMAIL_ALREADY_EXISTS = 105;
    int CART_NOT_EXISTS = 106;
    int INVALID_USER_PASSED = 107;
    int POTENITAL_ORDER_EXPIRED = 108;
    int INVALID_EVOUCHER = 109;
    int LOGIN_REQUIRED = 110;
    int BASKET_EMPTY = 112;
    int NO_ITEMS_IN_CART = 113;
    int LIST_SLUG_MISSING = 114;
    int PRODUCT_DOES_NOT_EXISTS = 115;
    int EMAIL_DOESNT_EXISTS = 116;
    int LIST_WITH_NAME_ALREADY_EXISTS = 117;
    int INVALID_INPUT = 119;
    int MEMBER_SHOPPING_LIST_DOESNT_EXISTS = 122;
    String AMOUNT_MISMATCH_STR = "123";
    int PROMO_NOT_EXIST = 123;
    int PROMO_CATEGORY_NOT_EXIST = 124;
    int PROMO_CRITERIA_SET_NOT_EXISTS = 125;
    int PROMO_NOT_ACTIVE = 126;
    int INVALID_PROMO = 127;
    int EMPTY_ADDRESS = 130;
    int ORDER_IN_PROGRESS = 131;
    int NUMBER_IN_USE = 180;
    int OTP_NEEDED = 181;
    int OTP_INVALID = 182;
    int NO_ACCOUNT = 183;
    int PRODUCT_QTY_LIMIT = 184;
    int ADDRESS_NOT_SERVED = 185;
    int INVALID_REFERRAL_CODE = 186;
}
